spring:
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  application:
    name: ai-code-mother-backend
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_ai_coding?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 10280017
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
langchain4j:
  community:
    dashscope:
      # 普通的 Chat 模型配置
      chat-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: deepseek-v3
        max-tokens: 8192
      # 流式 Chat 模型配置
      streaming-chat-model:
        chat-model:
          api-key: ${DASHSCOPE_API_KEY}
          model-name: deepseek-v3
          max-tokens: 8192
          stream: true  # 启用流式处理

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.example.aicodemother.controller

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "ai-coding"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.example.aicodemother.controller


